### ISSUE TITLE
Get rid of react-icons

### ISSUE THREAD

**Issue by luisherranz** [alexadark/frontity-starter-theme#1]
The package `react-icons` is adding 624Kb to the whole bundle:

<img width="1680" alt="Screen Shot 2020-03-30 at 08 37 35" src="https://user-images.githubusercontent.com/3305402/77883483-82340f00-7263-11ea-92db-60ae33c17eb7.png">

As you can see, it is almost as big as the rest of the app, react included.

You can see it yourself by inspecting the `build/analyze/module-production.html` file after running `npx frontity dev --production`. Don't forget the `--production` flag.

Normally, you can avoid this problem:
- Using modules with tree-shaking support. They have `sideEffects: false` in their package jsons: https://webpack.js.org/guides/tree-shaking/
- Picking directly the file from the bundle, like what we do for react-spinners in mars-theme:
```js
import Loader from "react-spinners/ScaleLoader";
// instead of
import { Loader } from "react-spinners";
```
https://github.com/frontity/frontity/blob/dev/packages/mars-theme/src/components/loading.js#L3

But in the case of `react-icons`, even though it uses `"sideEffects": false,` it is breaking it for the way it imports the ionicons internally. And also, for the weird way it imports those icons, there's no direct pick either, so this library should be avoided at all costs, at least the ionicons part.

**Comment by alexadark** [comment]
I have changed for react-icons-kit

**Comment by luisherranz** [comment]
Awesome :)

Let me know once you push the code and I'll take a look.

**Comment by alexadark** [comment]
All is pushed now :-)

**Comment by luisherranz** [comment]
Looks great 👍

**Comment by luisherranz** [comment]
For context, this was solved in https://github.com/alexadark/frontity-starter-theme/commit/b5c39bb6a3bcfaf26d8f780a641db163a6954180.
