### ISSUE TITLE
Choose between woff and woff2

### ISSUE THREAD

**Issue by luisherranz** [alexadark/frontity-starter-theme#2]
As you know, a font is embedded in Frontity's HTML if the font is smaller than 25Kbs.

Embedding fonts is great because you avoid an additional round trip to the server and the flash of unstyled content problem.

But when embedding fonts, I don' think that including both `woff` and `woff2` formats is the best approach, because you're doubling the Kbs of your fonts just to support a 2% more of browsers (IE11 and Android<4).

- https://caniuse.com/#search=woff
- https://caniuse.com/#search=woff2

<img width="352" alt="Screen Shot 2020-03-30 at 09 35 20" src="https://user-images.githubusercontent.com/3305402/77886815-cde9b700-7269-11ea-9dad-c25f0178762c.png">

In my opinion, it's best to choose woff2 because it is smaller and you're only leaving IE11 and old Android devices behind. It doesn't mean of course that those devices won't see the page, just that they will see it with a default font, so it's not critical.

In the case that you want to support those devices, I would choose `woff`, but never both.

**Comment by alexadark** [comment]
Done

**Comment by luisherranz** [comment]
Awesome, thanks. Closing this then.
