### ISSUE TITLE
Text logo not showing

### ISSUE THREAD

**Issue by luisherranz** [alexadark/frontity-starter-theme#9]
If you switch to text logo, it doesn't show up:

<img width="331" alt="Screen Shot 2020-04-01 at 12 01 14" src="https://user-images.githubusercontent.com/3305402/78124906-a1bc6a80-7410-11ea-80a7-f6587b6b9977.png">

**Comment by luisherranz** [comment]
This is solved now, isn't it @alexadark?

**Comment by Tikio88** [comment]
I know this is quite a long time ago, but I believe it is fixed @luisherranz as It worked for me. In case you haven't tested it again! 😄

**Comment by luisherranz** [comment]
Awesome, thanks @Tikio88 🙂
